name: Dependabot auto-merge

on:
  workflow_run:
    workflows:
      - ".NET CI"
    types:
      - completed

permissions:
  pull-requests: write
  contents: write

jobs:
  enable_auto_merge:
    name: Enable auto-merge
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Get PR URL
        id: pr-url
        uses: actions/github-script@v3
        with:
          result-encoding: string
          script: |
            const {owner, repo} = context.repo;
            const pull_head_sha = '${{ github.event.workflow_run.head_sha }}';

            const issue_number = await (async () => {
              const pulls = await github.pulls.list({owner, repo});
              for await (const {data} of github.paginate.iterator(pulls)) {
                for (const pull of data) {
                  if (pull.head.sha === pull_head_sha) {
                    return pull.number;
                  }
                }
              }
            })();

            if (issue_number) {
              core.info(`Using pull request ${issue_number}`);
            } else {
              return core.error(`No matching pull request found`);
            }

            return `${context.serverUrl}/${owner}/${repo}/pull/${issue_number}`;

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto -s "$PR_URL"
        env:
          PR_URL: ${{ steps.pr-url.outputs.result }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
