name: Dependabot auto-merge PRs
on:
  pull_request:
    paths-ignore:
      - ".github/workflows/**"

permissions:
  pull-requests: write
  contents: write
  checks: read

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Enable auto-merge for dependency update PRs
        run: gh pr merge --auto -s "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
